[2023-11-13 20:52:46,523] ERROR _log() L96   Error on request:
Traceback (most recent call last):
  File "/home/ubuntu/miniconda3/lib/python3.11/site-packages/werkzeug/serving.py", line 362, in run_wsgi
    execute(self.server.app)
  File "/home/ubuntu/miniconda3/lib/python3.11/site-packages/werkzeug/serving.py", line 323, in execute
    application_iter = app(environ, start_response)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/miniconda3/lib/python3.11/site-packages/flask/cli.py", line 906, in app
    raise err from None
  File "/home/ubuntu/miniconda3/lib/python3.11/site-packages/werkzeug/serving.py", line 362, in run_wsgi
    execute(self.server.app)
  File "/home/ubuntu/miniconda3/lib/python3.11/site-packages/werkzeug/serving.py", line 323, in execute
    application_iter = app(environ, start_response)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/miniconda3/lib/python3.11/site-packages/flask/cli.py", line 906, in app
    raise err from None
  File "/home/ubuntu/miniconda3/lib/python3.11/site-packages/werkzeug/serving.py", line 362, in run_wsgi
    execute(self.server.app)
  File "/home/ubuntu/miniconda3/lib/python3.11/site-packages/werkzeug/serving.py", line 323, in execute
    application_iter = app(environ, start_response)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/miniconda3/lib/python3.11/site-packages/flask/cli.py", line 906, in app
    raise err from None
  File "/home/ubuntu/miniconda3/lib/python3.11/site-packages/werkzeug/serving.py", line 362, in run_wsgi
    execute(self.server.app)
  File "/home/ubuntu/miniconda3/lib/python3.11/site-packages/werkzeug/serving.py", line 323, in execute
    application_iter = app(environ, start_response)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/miniconda3/lib/python3.11/site-packages/flask/cli.py", line 906, in app
    raise err from None
  File "/home/ubuntu/miniconda3/lib/python3.11/site-packages/werkzeug/serving.py", line 362, in run_wsgi
    execute(self.server.app)
  File "/home/ubuntu/miniconda3/lib/python3.11/site-packages/werkzeug/serving.py", line 323, in execute
    application_iter = app(environ, start_response)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/miniconda3/lib/python3.11/site-packages/flask/cli.py", line 906, in app
    raise err from None
  File "/home/ubuntu/miniconda3/lib/python3.11/site-packages/werkzeug/serving.py", line 362, in run_wsgi
    execute(self.server.app)
  File "/home/ubuntu/miniconda3/lib/python3.11/site-packages/werkzeug/serving.py", line 323, in execute
    application_iter = app(environ, start_response)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/miniconda3/lib/python3.11/site-packages/flask/cli.py", line 906, in app
    raise err from None
  File "/home/ubuntu/miniconda3/lib/python3.11/site-packages/flask/cli.py", line 897, in run_command
    app = info.load_app()
          ^^^^^^^^^^^^^^^
  File "/home/ubuntu/miniconda3/lib/python3.11/site-packages/flask/cli.py", line 312, in load_app
    app = locate_app(import_name, None, raise_if_not_found=False)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/miniconda3/lib/python3.11/site-packages/flask/cli.py", line 223, in locate_app
    raise NoAppException(
flask.cli.NoAppException: While importing 'app', an ImportError was raised:

Traceback (most recent call last):
  File "/home/ubuntu/miniconda3/lib/python3.11/site-packages/flask/cli.py", line 218, in locate_app
    __import__(module_name)
  File "/mnt/g/My Drive/Doutorado/Teaching/SoftEng4IntSysPos/exemplo_mvp/api/app.py", line 9, in <module>
    from schemas import *
  File "/mnt/g/My Drive/Doutorado/Teaching/SoftEng4IntSysPos/exemplo_mvp/api/schemas/__init__.py", line 1, in <module>
    from schemas.paciente_schema import PacienteSchema,  PacienteBuscaSchema, PacienteViewSchema, PacienteDelSchema, \
ImportError: cannot import name 'predict_diabetes' from 'schemas.paciente_schema' (/mnt/g/My Drive/Doutorado/Teaching/SoftEng4IntSysPos/exemplo_mvp/api/schemas/paciente_schema.py) - call_trace=/home/ubuntu/miniconda3/lib/python3.11/site-packages/werkzeug/_internal.py L96  
[2023-11-13 20:53:34,353] INFO _log() L96    * Detected change in '/mnt/g/My Drive/Doutorado/Teaching/SoftEng4IntSysPos/exemplo_mvp/api/schemas/paciente_schema.py', reloading - call_trace=/home/ubuntu/miniconda3/lib/python3.11/site-packages/werkzeug/_internal.py L96  
[2023-12-04 20:57:34,410] INFO _log() L96   [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000 - call_trace=/Users/lc.romao/miniconda3/lib/python3.11/site-packages/werkzeug/_internal.py L96  
[2023-12-04 20:57:34,410] INFO _log() L96   [33mPress CTRL+C to quit[0m - call_trace=/Users/lc.romao/miniconda3/lib/python3.11/site-packages/werkzeug/_internal.py L96  
[2023-12-04 20:57:34,411] INFO _log() L96    * Restarting with stat - call_trace=/Users/lc.romao/miniconda3/lib/python3.11/site-packages/werkzeug/_internal.py L96  
[2023-12-04 20:57:46,105] INFO _log() L96   127.0.0.1 - - [04/Dec/2023 20:57:46] "[32mGET / HTTP/1.1[0m" 302 - - call_trace=/Users/lc.romao/miniconda3/lib/python3.11/site-packages/werkzeug/_internal.py L96  
[2023-12-04 20:57:46,116] INFO _log() L96   127.0.0.1 - - [04/Dec/2023 20:57:46] "[32mGET /openapi HTTP/1.1[0m" 308 - - call_trace=/Users/lc.romao/miniconda3/lib/python3.11/site-packages/werkzeug/_internal.py L96  
[2023-12-04 20:57:46,131] INFO _log() L96   127.0.0.1 - - [04/Dec/2023 20:57:46] "GET /openapi/ HTTP/1.1" 200 - - call_trace=/Users/lc.romao/miniconda3/lib/python3.11/site-packages/werkzeug/_internal.py L96  
[2023-12-04 20:57:46,173] INFO _log() L96   127.0.0.1 - - [04/Dec/2023 20:57:46] "GET /openapi/static/images/swagger.svg HTTP/1.1" 200 - - call_trace=/Users/lc.romao/miniconda3/lib/python3.11/site-packages/werkzeug/_internal.py L96  
[2023-12-04 20:57:46,173] INFO _log() L96   127.0.0.1 - - [04/Dec/2023 20:57:46] "GET /openapi/static/images/redoc.svg HTTP/1.1" 200 - - call_trace=/Users/lc.romao/miniconda3/lib/python3.11/site-packages/werkzeug/_internal.py L96  
[2023-12-04 20:57:46,378] INFO _log() L96   127.0.0.1 - - [04/Dec/2023 20:57:46] "GET /openapi/static/images/rapidoc.svg HTTP/1.1" 200 - - call_trace=/Users/lc.romao/miniconda3/lib/python3.11/site-packages/werkzeug/_internal.py L96  
[2023-12-04 20:57:46,458] INFO _log() L96   127.0.0.1 - - [04/Dec/2023 20:57:46] "GET /openapi/static/images/apidoc.svg HTTP/1.1" 200 - - call_trace=/Users/lc.romao/miniconda3/lib/python3.11/site-packages/werkzeug/_internal.py L96  
[2023-12-04 20:57:46,517] INFO _log() L96   127.0.0.1 - - [04/Dec/2023 20:57:46] "[36mGET /openapi/static/images/apidoc.svg HTTP/1.1[0m" 304 - - call_trace=/Users/lc.romao/miniconda3/lib/python3.11/site-packages/werkzeug/_internal.py L96  
[2023-12-04 20:57:47,556] INFO _log() L96   127.0.0.1 - - [04/Dec/2023 20:57:47] "GET /openapi/swagger HTTP/1.1" 200 - - call_trace=/Users/lc.romao/miniconda3/lib/python3.11/site-packages/werkzeug/_internal.py L96  
[2023-12-04 20:57:47,601] INFO _log() L96   127.0.0.1 - - [04/Dec/2023 20:57:47] "GET /openapi/static/css/swagger-ui.css HTTP/1.1" 200 - - call_trace=/Users/lc.romao/miniconda3/lib/python3.11/site-packages/werkzeug/_internal.py L96  
[2023-12-04 20:57:47,603] INFO _log() L96   127.0.0.1 - - [04/Dec/2023 20:57:47] "GET /openapi/static/js/swagger-ui-bundle.js HTTP/1.1" 200 - - call_trace=/Users/lc.romao/miniconda3/lib/python3.11/site-packages/werkzeug/_internal.py L96  
[2023-12-04 20:57:47,603] INFO _log() L96   127.0.0.1 - - [04/Dec/2023 20:57:47] "GET /openapi/static/js/swagger-ui-standalone-preset.js HTTP/1.1" 200 - - call_trace=/Users/lc.romao/miniconda3/lib/python3.11/site-packages/werkzeug/_internal.py L96  
[2023-12-04 20:57:47,870] INFO _log() L96   127.0.0.1 - - [04/Dec/2023 20:57:47] "[36mGET /openapi/static/images/swagger.svg HTTP/1.1[0m" 304 - - call_trace=/Users/lc.romao/miniconda3/lib/python3.11/site-packages/werkzeug/_internal.py L96  
[2023-12-04 20:57:47,907] INFO _log() L96   127.0.0.1 - - [04/Dec/2023 20:57:47] "GET /openapi/openapi.json HTTP/1.1" 200 - - call_trace=/Users/lc.romao/miniconda3/lib/python3.11/site-packages/werkzeug/_internal.py L96  
[2023-12-04 20:57:47,920] INFO _log() L96   127.0.0.1 - - [04/Dec/2023 20:57:47] "[36mGET /openapi/static/images/swagger.svg HTTP/1.1[0m" 304 - - call_trace=/Users/lc.romao/miniconda3/lib/python3.11/site-packages/werkzeug/_internal.py L96  
[2023-12-04 20:58:02,138] WARNING get_pacientes() L50   N√£o h√° pacientes cadastrados na base :/ - call_trace=/Users/lc.romao/Library/CloudStorage/GoogleDrive-lc.romao98@gmail.com/My Drive/Doutorado/Teaching/engenharia-de-software/mvp-qualidade-seguranca-sistemas-inteligentes/exemplo_mvp/api/app.py L50  
[2023-12-04 20:58:02,139] INFO _log() L96   127.0.0.1 - - [04/Dec/2023 20:58:02] "[33mGET /pacientes HTTP/1.1[0m" 404 - - call_trace=/Users/lc.romao/miniconda3/lib/python3.11/site-packages/werkzeug/_internal.py L96  
[2023-12-04 20:58:26,275] WARNING get_pacientes() L50   N√£o h√° pacientes cadastrados na base :/ - call_trace=/Users/lc.romao/Library/CloudStorage/GoogleDrive-lc.romao98@gmail.com/My Drive/Doutorado/Teaching/engenharia-de-software/mvp-qualidade-seguranca-sistemas-inteligentes/exemplo_mvp/api/app.py L50  
[2023-12-04 20:58:26,276] INFO _log() L96   127.0.0.1 - - [04/Dec/2023 20:58:26] "[33mGET /pacientes HTTP/1.1[0m" 404 - - call_trace=/Users/lc.romao/miniconda3/lib/python3.11/site-packages/werkzeug/_internal.py L96  
[2023-12-04 20:58:26,559] WARNING get_pacientes() L50   N√£o h√° pacientes cadastrados na base :/ - call_trace=/Users/lc.romao/Library/CloudStorage/GoogleDrive-lc.romao98@gmail.com/My Drive/Doutorado/Teaching/engenharia-de-software/mvp-qualidade-seguranca-sistemas-inteligentes/exemplo_mvp/api/app.py L50  
